/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      sm: '480px',    // var(--breakpoint-sm)
      md: '768px',    // var(--breakpoint-md)
      lg: '1024px',   // var(--breakpoint-lg)
      xl: '1280px',   // var(--breakpoint-xl)
      '2xl': '1440px',// var(--breakpoint-2xl)
    },
    extend: {
      fontFamily: {
        heading: ['var(--font-family-heading)', 'Georgia', 'serif'],
        body: ['var(--font-family-body)', 'sans-serif'],
        sans: ['var(--font-family-body)', 'sans-serif'],
        serif: ['var(--font-family-heading)', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-xl': ['var(--font-size-display-xl)', { lineHeight: 'var(--line-height-tight)', fontWeight: '700' }],
        'display-lg': ['var(--font-size-display-lg)', { lineHeight: 'var(--line-height-tight)', fontWeight: '700' }],
        'heading-xl': ['var(--font-size-heading-xl)', { lineHeight: 'var(--line-height-heading)', fontWeight: '700' }],
        'heading-lg': ['var(--font-size-heading-lg)', { lineHeight: 'var(--line-height-heading)', fontWeight: '700' }],
        'heading-md': ['var(--font-size-heading-md)', { lineHeight: 'var(--line-height-heading)', fontWeight: '700' }],
        'heading-sm': ['var(--font-size-heading-sm)', { lineHeight: 'var(--line-height-heading)', fontWeight: '700' }],
        'body-lg': ['var(--font-size-body-lg)', { lineHeight: 'var(--line-height-relaxed)', fontWeight: '400' }],
        'body-md': ['var(--font-size-body-md)', { lineHeight: 'var(--line-height-body)', fontWeight: '400' }],
        'body-sm': ['var(--font-size-body-sm)', { lineHeight: 'var(--line-height-body)', fontWeight: '400' }],
        'caption': ['var(--font-size-caption)', { lineHeight: '1.4', fontWeight: '500' }],
        'button-lg': ['var(--font-size-button-lg)', { lineHeight: '1.0', fontWeight: '600' }],
        'button-md': ['var(--font-size-button-md)', { lineHeight: '1.0', fontWeight: '600' }],
        'button-sm': ['var(--font-size-button-sm)', { lineHeight: '1.0', fontWeight: '600' }],
        'input-md': ['var(--font-size-input-md)', { lineHeight: '1.4', fontWeight: '400' }],
      },
      colors: {
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          active: 'var(--color-primary-active)',
          soft: 'var(--color-primary-soft)',
        },
        gold: {
          50: 'var(--color-gold-50)',
          100: 'var(--color-gold-100)',
          200: 'var(--color-gold-200)',
          300: 'var(--color-gold-300)',
          400: 'var(--color-gold-400)',
          500: 'var(--color-gold-500)',
          600: 'var(--color-gold-600)',
          700: 'var(--color-gold-700)',
          800: 'var(--color-gold-800)',
        },
        neutral: {
          0: 'var(--color-neutral-0)',
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
        },
        success: {
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          DEFAULT: 'var(--color-success)',
          soft: 'var(--color-success-soft)',
        },
        error: {
          50: 'var(--color-error-50)',
          100: 'var(--color-error-100)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          DEFAULT: 'var(--color-error)',
          soft: 'var(--color-error-soft)',
        },
        warning: {
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          DEFAULT: 'var(--color-warning)',
          soft: 'var(--color-warning-soft)',
        },
        info: {
          50: 'var(--color-info-50)',
          100: 'var(--color-info-100)',
          500: 'var(--color-info-500)',
          600: 'var(--color-info-600)',
          700: 'var(--color-info-700)',
          DEFAULT: 'var(--color-info)',
          soft: 'var(--color-info-soft)',
        },
        game: {
          purple: 'var(--game-purple)',
          blue: 'var(--game-blue)',
          cyan: 'var(--game-cyan)',
          orange: 'var(--game-orange)',
          gold: 'var(--game-gold)',
          pink: 'var(--game-pink)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          soft: 'var(--color-accent-soft)',
        },
        bg: {
          page: 'var(--color-bg-page)',
          surface: 'var(--color-bg-surface)',
          muted: 'var(--color-bg-muted)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          inverse: 'var(--color-text-inverse)',
        },
        border: {
          default: 'var(--color-border-default)',
          strong: 'var(--color-border-strong)',
        },
      },
      spacing: {
        '0': 'var(--space-0)',
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        header: 'var(--z-header)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        emphasized: 'var(--ease-emphasized)',
      },
      minHeight: {
        'touch-min': 'var(--touch-target-min)',
        'touch-comfortable': 'var(--touch-target-comfortable)',
        'touch-large': 'var(--touch-target-large)',
        'touch-parent': 'var(--touch-target-parent)',
        'button-sm': 'var(--button-height-sm)',
        'button-md': 'var(--button-height-md)',
        'button-lg': 'var(--button-height-lg)',
        'button-parent': 'var(--button-height-parent)',
        'input-sm': 'var(--input-height-sm)',
        'input-md': 'var(--input-height-md)',
        'input-lg': 'var(--input-height-lg)',
        'input-parent': 'var(--input-height-parent)',
      },
      minWidth: {
        'touch-min': 'var(--touch-target-min)',
        'touch-comfortable': 'var(--touch-target-comfortable)',
        'touch-large': 'var(--touch-target-large)',
        'touch-parent': 'var(--touch-target-parent)',
      },
    },
  },
  plugins: [],
};
