import { Student, ClassInfo, NotificationData } from "../types";
import { ActivityItem } from "../components/dashboard/ActivityFeed";
import { AchievementBadgeProps } from "../components/gamification/AchievementBadge";

// ============================================================================
// MOCK CLASSES (§20, §30)
// ============================================================================
export const MOCK_CLASSES: (ClassInfo & {
  presentCount: number;
  attendanceRate: number;
  lastUpdated: string;
})[] = [
  {
    id: "cls-7a",
    name: "Lớp 7A",
    grade: "Khối Thêm Sức 1",
    academicYear: "2026 - 2027",
    studentCount: 32,
    teachers: ["GLV. Maria Nguyễn Thị Hoa", "GLV. Giuse Trần Văn Minh"],
    room: "Phòng 201 - Nhà Mục Vụ",
    presentCount: 30,
    attendanceRate: 94,
    lastUpdated: "10 phút trước",
  },
  {
    id: "cls-8a",
    name: "Lớp 8A",
    grade: "Khối Thêm Sức 2",
    academicYear: "2026 - 2027",
    studentCount: 28,
    teachers: ["GLV. Phêrô Lê Minh Cường"],
    room: "Phòng 202 - Nhà Mục Vụ",
    presentCount: 27,
    attendanceRate: 96,
    lastUpdated: "25 phút trước",
  },
  {
    id: "cls-3b",
    name: "Lớp 3B",
    grade: "Khối Rước Lễ 1",
    academicYear: "2026 - 2027",
    studentCount: 35,
    teachers: ["GLV. Maria Nguyễn Thị Lan", "GLV. Têrêsa Mai"],
    room: "Phòng 104 - Tầng trệt",
    presentCount: 34,
    attendanceRate: 97,
    lastUpdated: "40 phút trước",
  },
  {
    id: "cls-4a",
    name: "Lớp 4A",
    grade: "Khối Rước Lễ 2",
    academicYear: "2026 - 2027",
    studentCount: 30,
    teachers: ["GLV. Antôn Đỗ Hoàng Nam"],
    room: "Phòng 105 - Tầng trệt",
    presentCount: 26,
    attendanceRate: 87, // Cảnh báo vắng > 10%
    lastUpdated: "1 giờ trước",
  },
  {
    id: "cls-cc1",
    name: "Lớp Chiên Con 1",
    grade: "Khối Khai Tâm",
    academicYear: "2026 - 2027",
    studentCount: 24,
    teachers: ["GLV. Anna Vũ Thị Hồng"],
    room: "Hội trường Thiếu nhi",
    presentCount: 21,
    attendanceRate: 88,
    lastUpdated: "2 giờ trước",
  },
  {
    id: "cls-bb1",
    name: "Lớp Bao Đồng 1",
    grade: "Khối Bao Đồng",
    academicYear: "2026 - 2027",
    studentCount: 26,
    teachers: ["GLV. Gioan Baotixita Quang"],
    room: "Phòng 301 - Tầng 3",
    presentCount: 22,
    attendanceRate: 85, // Cảnh báo vắng > 10%
    lastUpdated: "Hôm qua",
  },
];

// ============================================================================
// MOCK STUDENTS (§19)
// ============================================================================
export const MOCK_STUDENTS: Student[] = [
  {
    id: "stu-001",
    code: "HS001",
    orderNumber: 1,
    name: "Nguyễn Văn An",
    christianName: "Giuse",
    gender: "MALE",
    className: "Lớp 7A",
    classId: "cls-7a",
    parentName: "Nguyễn Văn Bình",
    parentPhone: "0903123456",
  },
  {
    id: "stu-002",
    code: "HS002",
    orderNumber: 2,
    name: "Trần Thị Bích",
    christianName: "Maria",
    gender: "FEMALE",
    className: "Lớp 7A",
    classId: "cls-7a",
    parentName: "Trần Văn Cường",
    parentPhone: "0918765432",
  },
  {
    id: "stu-003",
    code: "HS003",
    orderNumber: 3,
    name: "Lê Minh Cường",
    christianName: "Phêrô",
    gender: "MALE",
    className: "Lớp 7A",
    classId: "cls-7a",
    parentName: "Lê Văn Dũng",
    parentPhone: "0982345678",
  },
  {
    id: "stu-004",
    code: "HS004",
    orderNumber: 4,
    name: "Phạm Thùy Dương",
    christianName: "Têrêsa",
    gender: "FEMALE",
    className: "Lớp 7A",
    classId: "cls-7a",
    parentName: "Phạm Hữu Đạt",
    parentPhone: "0971239874",
  },
  {
    id: "stu-005",
    code: "HS005",
    orderNumber: 5,
    name: "Đỗ Hoàng Long",
    christianName: "Phanxicô",
    gender: "MALE",
    className: "Lớp 7A",
    classId: "cls-7a",
    parentName: "Đỗ Quốc Hùng",
    parentPhone: "0934567890",
  },
  {
    id: "stu-006",
    code: "HS006",
    orderNumber: 6,
    name: "Vũ Mai Linh",
    christianName: "Anna",
    gender: "FEMALE",
    className: "Lớp 7A",
    classId: "cls-7a",
    parentName: "Vũ Trọng Phụng",
    parentPhone: "0912345999",
  },
  {
    id: "stu-007",
    code: "HS007",
    orderNumber: 7,
    name: "Hoàng Gia Huy",
    christianName: "Gioan Baotixita",
    gender: "MALE",
    className: "Lớp 7A",
    classId: "cls-7a",
    parentName: "Hoàng Văn Tuấn",
    parentPhone: "0908876543",
  },
  {
    id: "stu-008",
    code: "HS008",
    orderNumber: 8,
    name: "Đinh Phương Thảo",
    christianName: "Maria Madalena",
    gender: "FEMALE",
    className: "Lớp 7A",
    classId: "cls-7a",
    parentName: "Đinh Xuân Trường",
    parentPhone: "0943210987",
  },
  {
    id: "stu-009",
    code: "HS009",
    orderNumber: 9,
    name: "Bùi Tuấn Kiệt",
    christianName: "Antôn",
    gender: "MALE",
    className: "Lớp 7A",
    classId: "cls-7a",
    parentName: "Bùi Quốc Khánh",
    parentPhone: "0965432109",
  },
  {
    id: "stu-010",
    code: "HS010",
    orderNumber: 10,
    name: "Ngô Ánh Tuyết",
    christianName: "Cêcilia",
    gender: "FEMALE",
    className: "Lớp 7A",
    classId: "cls-7a",
    parentName: "Ngô Đình Diệm",
    parentPhone: "0977889900",
  },
  {
    id: "stu-011",
    code: "HS011",
    orderNumber: 1,
    name: "Nguyễn Thị Mai Anh",
    christianName: "Maria",
    gender: "FEMALE",
    className: "Lớp 3B",
    classId: "cls-3b",
  },
  {
    id: "stu-012",
    code: "HS012",
    orderNumber: 2,
    name: "Trần Quốc Toản",
    christianName: "Giuse",
    gender: "MALE",
    className: "Lớp 3B",
    classId: "cls-3b",
  },
];

// ============================================================================
// MOCK ACTIVITIES (§25, Wireframe A §4–5)
// ============================================================================
export const MOCK_ADMIN_ACTIVITIES: ActivityItem[] = [
  {
    id: "act-1",
    userName: "Nguyễn Văn An",
    christianName: "GLV. Giuse",
    userRole: "GLV",
    action: "Cập nhật điểm kiểm tra 15 phút",
    target: "Lớp 7A",
    time: "10 phút trước",
    type: "score",
  },
  {
    id: "act-2",
    userName: "Trần Văn Bình",
    christianName: "GLV. Phêrô",
    userRole: "GLV",
    action: "Đã điểm danh Chúa Nhật 24/09",
    target: "Lớp 8A",
    time: "25 phút trước",
    type: "attendance",
  },
  {
    id: "act-3",
    userName: "Maria Nguyễn Thị Lan",
    christianName: "GLV. Maria",
    userRole: "GLV",
    action: "Hoàn tất nhập điểm Giữa kỳ I",
    target: "Lớp 3B",
    time: "40 phút trước",
    type: "score",
  },
  {
    id: "act-4",
    userName: "Ban Quản Trị Xứ Đoàn",
    userRole: "ADMIN",
    action: "Phát hành thông báo khẩn Tĩnh tâm",
    target: "Khối Thêm Sức",
    time: "1 giờ trước",
    type: "notification",
  },
  {
    id: "act-5",
    userName: "Antôn Đỗ Hoàng Nam",
    christianName: "GLV. Antôn",
    userRole: "GLV",
    action: "Đã điểm danh và gửi báo cáo vắng",
    target: "Lớp 4A",
    time: "2 giờ trước",
    type: "attendance",
  },
];

export const MOCK_TEACHER_ACTIVITIES: ActivityItem[] = [
  {
    id: "act-t1",
    userName: "Maria Nguyễn Thị Hoa",
    christianName: "GLV",
    userRole: "Phụ trách",
    action: "Đã lưu bảng điểm danh Chúa Nhật 24/09",
    target: "30/32 có mặt",
    time: "15 phút trước",
    type: "attendance",
  },
  {
    id: "act-t2",
    userName: "Giuse Trần Văn Minh",
    christianName: "GLV",
    userRole: "Đồng hành",
    action: "Đã chấm điểm miệng cho 12 học sinh",
    target: "Môn Kinh Thánh",
    time: "1 giờ trước",
    type: "score",
  },
  {
    id: "act-t3",
    userName: "Ban Huynh Trưởng",
    userRole: "ADMIN",
    action: "Nhắc nhở nộp danh sách vắng phép tháng 9",
    target: "Lớp 7A",
    time: "Hôm qua",
    type: "notification",
  },
];

// ============================================================================
// MOCK NOTIFICATIONS FOR ADMIN
// ============================================================================
export const MOCK_ADMIN_NOTIFICATIONS: NotificationData[] = [
  {
    id: "admin-alert-1",
    type: "URGENT",
    title: "Cảnh báo: 3 lớp có tỷ lệ vắng > 10% hôm nay",
    preview: "Lớp 4A (87%), Lớp Chiên Con 1 (88%), Lớp Bao Đồng 1 (85%) cần được GLV liên hệ phụ huynh.",
    content: "Hệ thống ghi nhận tỷ lệ chuyên cần dưới ngưỡng tiêu chuẩn 90% tại 3 lớp. Đề nghị Ban Quản trị đôn đốc Giáo lý viên chủ nhiệm kiểm tra tình hình phụ huynh xin phép.",
    timestamp: "15 phút trước",
    formattedDate: "24/09/2026 · 08:45",
    isRead: false,
    className: "Toàn xứ đoàn",
    actionLabel: "Kiểm tra danh sách vắng",
  },
  {
    id: "admin-alert-2",
    type: "SYSTEM",
    title: "Kỳ thi Giáo lý Học kỳ I: Hạn chót nộp đề thi",
    preview: "Còn 3 ngày để các Phân đoàn nộp đề thi trắc nghiệm và tự luận về Ban Giáo lý.",
    content: "Kính báo quý GLV Trưởng ban và Phân đoàn trưởng, hạn chót nộp đề thi Giáo lý và Kinh Thánh là ngày 27/09/2026.",
    timestamp: "1 ngày trước",
    formattedDate: "23/09/2026 · 10:00",
    isRead: false,
    actionLabel: "Xem hướng dẫn ra đề",
  },
];

// ============================================================================
// MOCK GAMIFICATION ASSETS (§26 - STRICTLY FOR STUDENT AREA ONLY!)
// ============================================================================
export const MOCK_ACHIEVEMENTS: AchievementBadgeProps[] = [
  {
    id: "ach-1",
    title: "Chuyên cần Vàng",
    description: "Tham dự Thánh lễ và giờ học Giáo lý đầy đủ 8 tuần liên tiếp không vắng.",
    icon: "⭐",
    status: "UNLOCKED",
    xpReward: 300,
    unlockedAt: "18/09/2026",
    rarity: "EPIC",
  },
  {
    id: "ach-2",
    title: "Hiệp sĩ Lời Chúa",
    description: "Đạt điểm 10 kiểm tra miệng môn Kinh Thánh và thuộc 5 câu Lời Chúa cốt lõi.",
    icon: "📖",
    status: "NEW",
    xpReward: 250,
    unlockedAt: "Hôm nay",
    rarity: "LEGENDARY",
  },
  {
    id: "ach-3",
    title: "Bác ái Vui tươi",
    description: "Tích cực giúp đỡ bạn bè trong lớp và đóng góp phong trào Nuôi heo đất xứ đoàn.",
    icon: "🕊️",
    status: "AVAILABLE",
    xpReward: 150,
    rarity: "RARE",
  },
  {
    id: "ach-4",
    title: "Cầu nguyện Sốt sắng",
    description: "Đọc kinh gia đình 14 ngày liên tiếp và tham gia giờ chầu Thánh Thể đầu tháng.",
    icon: "🕯️",
    status: "LOCKED",
    xpReward: 200,
    rarity: "EPIC",
  },
  {
    id: "ach-5",
    title: "Ngôi sao Phụng vụ",
    description: "Tham gia giúp lễ hoặc hát ca đoàn thiếu nhi chăm chỉ trong suốt niên khóa.",
    icon: "👑",
    status: "LOCKED",
    xpReward: 500,
    rarity: "LEGENDARY",
  },
];
